Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true